package com.flowframe.app.ui.theme

import androidx.compose.ui.graphics.Color

internal val FlowPrimaryLight = Color(0xFF5857D9)
internal val FlowOnPrimaryLight = Color(0xFFFFFFFF)
internal val FlowPrimaryContainerLight = Color(0xFFE3E0FF)
internal val FlowOnPrimaryContainerLight = Color(0xFF181653)
internal val FlowSecondaryLight = Color(0xFF008F8D)
internal val FlowOnSecondaryLight = Color(0xFFFFFFFF)
internal val FlowSecondaryContainerLight = Color(0xFF9CF2EF)
internal val FlowOnSecondaryContainerLight = Color(0xFF00201F)
internal val FlowTertiaryLight = Color(0xFFC84F91)
internal val FlowBackgroundLight = Color(0xFFF7F8FC)
internal val FlowSurfaceLight = Color(0xFFF7F8FC)
internal val FlowSurfaceVariantLight = Color(0xFFE4E3EC)
internal val FlowOnSurfaceLight = Color(0xFF191A22)
internal val FlowOnSurfaceVariantLight = Color(0xFF46464F)
internal val FlowOutlineLight = Color(0xFF777680)
internal val FlowErrorLight = Color(0xFFBA1A1A)

internal val FlowPrimaryDark = Color(0xFFBBB9FF)
internal val FlowOnPrimaryDark = Color(0xFF28266F)
internal val FlowPrimaryContainerDark = Color(0xFF403F8D)
internal val FlowOnPrimaryContainerDark = Color(0xFFE3E0FF)
internal val FlowSecondaryDark = Color(0xFF6EDBD6)
internal val FlowOnSecondaryDark = Color(0xFF003735)
internal val FlowSecondaryContainerDark = Color(0xFF00504E)
internal val FlowOnSecondaryContainerDark = Color(0xFF9CF2EF)
internal val FlowTertiaryDark = Color(0xFFFFA1CE)
internal val FlowBackgroundDark = Color(0xFF0B0D12)
internal val FlowSurfaceDark = Color(0xFF0B0D12)
internal val FlowSurfaceVariantDark = Color(0xFF46464F)
internal val FlowOnSurfaceDark = Color(0xFFE6E8F0)
internal val FlowOnSurfaceVariantDark = Color(0xFFC7C5D0)
internal val FlowOutlineDark = Color(0xFF918F9A)
internal val FlowErrorDark = Color(0xFFFFB4AB)

internal val FlowGradientStart = Color(0xFF6B67F2)
internal val FlowGradientEnd = Color(0xFF00AAA5)
internal val DouyinAccent = Color(0xFF2DD4BF)
internal val BilibiliAccent = Color(0xFF36A9E1)
