"""Generate the Android vector branding assets without raster dependencies."""

from pathlib import Path

RES = Path(__file__).resolve().parents[1] / "app/src/main/res"
BACKGROUND = "#5956DB"
MARK = '''    <path android:fillColor="#B9B9FF"
        android:pathData="M42,29 L66,29 C71.5,29 76,33.5 76,39 L76,56 L38,56 L38,33 C38,30.8 39.8,29 42,29 Z" />
    <path android:fillColor="#FFFFFF"
        android:pathData="M38,36 L64,36 C69,36 73,40 73,45 L73,65 C73,70 69,74 64,74 L38,74 C33,74 29,70 29,65 L29,45 C29,40 33,36 38,36 Z" />
    <path android:fillColor="#5956DB"
        android:pathData="M43,46.5 C43,45.3 44.3,44.6 45.3,45.2 L57.7,52.7 C58.7,53.3 58.7,54.7 57.7,55.3 L45.3,62.8 C44.3,63.4 43,62.7 43,61.5 Z" />
    <path android:fillColor="#5956DB"
        android:pathData="M79,66 A13,13 0,1 1,53,66 A13,13 0,1 1,79,66 Z" />
    <path android:fillColor="#8DE5D4"
        android:pathData="M77,66 A11,11 0,1 1,55,66 A11,11 0,1 1,77,66 Z" />
    <path android:fillColor="@android:color/transparent"
        android:strokeColor="#28286B" android:strokeWidth="2.8"
        android:strokeLineCap="round" android:strokeLineJoin="round"
        android:pathData="M66,60 L66,71 M61.5,66.5 L66,71 L70.5,66.5" />'''

MONOCHROME = '''    <path android:fillColor="#FFFFFF"
        android:pathData="M42,29 L66,29 C71.5,29 76,33.5 76,39 L76,49 L73,49 L73,39 C73,35.1 69.9,32 66,32 L42,32 Z" />
    <path android:fillColor="#FFFFFF" android:fillType="evenOdd"
        android:pathData="M38,36 L64,36 C69,36 73,40 73,45 L73,51 C63,47 51,54 51,66 C51,69 51.7,71.7 53,74 L38,74 C33,74 29,70 29,65 L29,45 C29,40 33,36 38,36 Z M43,46.5 C43,45.3 44.3,44.6 45.3,45.2 L55.2,52.7 C56.2,53.3 56.2,54.7 55.2,55.3 L45.3,62.8 C44.3,63.4 43,62.7 43,61.5 Z" />
    <path android:fillColor="#FFFFFF" android:fillType="evenOdd"
        android:pathData="M77,66 A11,11 0,1 1,55,66 A11,11 0,1 1,77,66 Z M64.5,59 L67.5,59 L67.5,67.4 L69.5,65.4 L71.6,67.5 L66,73.1 L60.4,67.5 L62.5,65.4 L64.5,67.4 Z" />'''

TILE = f'''    <path android:fillColor="{BACKGROUND}"
        android:pathData="M30,4 L78,4 C95,4 104,13 104,30 L104,78 C104,95 95,104 78,104 L30,104 C13,104 4,95 4,78 L4,30 C4,13 13,4 30,4 Z" />'''


def vector(body: str, size: int = 108, viewport: int = 108) -> str:
    return f'''<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by tools/generate_brand_icons.py. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="{size}dp" android:height="{size}dp"
    android:viewportWidth="{viewport}" android:viewportHeight="{viewport}">
{body}
</vector>
'''


def write(relative: str, content: str) -> None:
    (RES / relative).write_text(content, encoding="utf-8", newline="\n")


def main() -> None:
    # Artwork stays within the central 66dp safe circle of the 108dp adaptive canvas.
    write("drawable/ic_launcher_foreground.xml", vector(MARK))
    write("drawable/ic_launcher_monochrome.xml", vector(MONOCHROME))
    # A legacy icon displays its full canvas; enlarge the same artwork accordingly.
    brand = TILE + '\n    <group android:pivotX="54" android:pivotY="54" android:scaleX="1.33" android:scaleY="1.33">\n' + MARK + '\n    </group>'
    write("drawable/ic_brand.xml", vector(brand, size=48))
    legacy = '''<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by tools/generate_brand_icons.py. -->
<layer-list xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:drawable="@drawable/ic_brand" />
</layer-list>
'''
    for name in ("ic_launcher", "ic_launcher_round"):
        write(f"mipmap-anydpi/{name}.xml", legacy)
    write("values/colors.xml", f'''<?xml version="1.0" encoding="utf-8"?>
<resources>
    <color name="launcher_background">{BACKGROUND}</color>
</resources>
''')
    # Notifications need a transparent monochrome symbol, not the launcher badge.
    notification = '''    <path android:fillColor="@android:color/transparent"
        android:strokeColor="#FFFFFF" android:strokeWidth="2"
        android:strokeLineCap="round" android:strokeLineJoin="round"
        android:pathData="M12,3 L12,15 M7,10 L12,15 L17,10 M5,16 L5,19 C5,20.1 5.9,21 7,21 L17,21 C18.1,21 19,20.1 19,19 L19,16" />'''
    write("drawable/ic_notification_download.xml", vector(notification, size=24, viewport=24))


if __name__ == "__main__":
    main()
